package HadithOntology.impl;

import HadithOntology.*;


import java.net.URI;
import java.util.Collection;
//import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultHadithChapter <br>
 * @version generated on Sun Jan 09 12:58:46 PKT 2022 by amna
 */
public class DefaultHadithChapter extends WrappedIndividualImpl implements HadithChapter {

    public DefaultHadithChapter(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#hasHadith
     */
     
    public Collection<? extends Hadith> getHasHadith() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASHADITH,
                                               DefaultHadith.class);
    }

    public boolean hasHasHadith() {
	   return !getHasHadith().isEmpty();
    }

    public void addHasHadith(Hadith newHasHadith) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASHADITH,
                                       newHasHadith);
    }

    public void removeHasHadith(Hadith oldHasHadith) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASHADITH,
                                          oldHasHadith);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#hasHadithType
     */
     
    public Collection<? extends HadithType> getHasHadithType() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASHADITHTYPE,
                                               DefaultHadithType.class);
    }

    public boolean hasHasHadithType() {
	   return !getHasHadithType().isEmpty();
    }

    public void addHasHadithType(HadithType newHasHadithType) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASHADITHTYPE,
                                       newHasHadithType);
    }

    public void removeHasHadithType(HadithType oldHasHadithType) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASHADITHTYPE,
                                          oldHasHadithType);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#hasNarrator
     */
     
    public Collection<? extends WrappedIndividual> getHasNarrator() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASNARRATOR,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasNarrator() {
	   return !getHasNarrator().isEmpty();
    }

    public void addHasNarrator(WrappedIndividual newHasNarrator) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASNARRATOR,
                                       newHasNarrator);
    }

    public void removeHasNarrator(WrappedIndividual oldHasNarrator) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASNARRATOR,
                                          oldHasNarrator);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#hasPart
     */
     
    public Collection<? extends WrappedIndividual> getHasPart() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASPART,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasPart() {
	   return !getHasPart().isEmpty();
    }

    public void addHasPart(WrappedIndividual newHasPart) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASPART,
                                       newHasPart);
    }

    public void removeHasPart(WrappedIndividual oldHasPart) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASPART,
                                          oldHasPart);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#hasRootNarrator
     */
     
    public Collection<? extends WrappedIndividual> getHasRootNarrator() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASROOTNARRATOR,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasRootNarrator() {
	   return !getHasRootNarrator().isEmpty();
    }

    public void addHasRootNarrator(WrappedIndividual newHasRootNarrator) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASROOTNARRATOR,
                                       newHasRootNarrator);
    }

    public void removeHasRootNarrator(WrappedIndividual oldHasRootNarrator) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASROOTNARRATOR,
                                          oldHasRootNarrator);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#hasRootNarratorOccurrence
     */
     
    public Collection<? extends WrappedIndividual> getHasRootNarratorOccurrence() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASROOTNARRATORSEGMENT,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasRootNarratorOccurrence() {
	   return !getHasRootNarratorOccurrence().isEmpty();
    }

    public void addHasRootNarratorOccurrence(WrappedIndividual newHasRootNarratorOccurrence) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASROOTNARRATORSEGMENT,
                                       newHasRootNarratorOccurrence);
    }

    public void removeHasRootNarratorOccurrence(WrappedIndividual oldHasRootNarratorOccurrence) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASROOTNARRATORSEGMENT,
                                          oldHasRootNarratorOccurrence);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#isPartOf
     */
     
    public Collection<? extends WrappedIndividual> getIsPartOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISPARTOF,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasIsPartOf() {
	   return !getIsPartOf().isEmpty();
    }

    public void addIsPartOf(WrappedIndividual newIsPartOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISPARTOF,
                                       newIsPartOf);
    }

    public void removeIsPartOf(WrappedIndividual oldIsPartOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISPARTOF,
                                          oldIsPartOf);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#isPartOfBook
     */
     
    public Collection<? extends HadithBook> getIsPartOfBook() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISPARTOFBOOK,
                                               DefaultHadithBook.class);
    }

    public boolean hasIsPartOfBook() {
	   return !getIsPartOfBook().isEmpty();
    }

    public void addIsPartOfBook(HadithBook newIsPartOfBook) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISPARTOFBOOK,
                                       newIsPartOfBook);
    }

    public void removeIsPartOfBook(HadithBook oldIsPartOfBook) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISPARTOFBOOK,
                                          oldIsPartOfBook);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#mentions
     */
     
    public Collection<? extends Hadith> getMentions() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_MENTIONS,
                                               DefaultHadith.class);
    }

    public boolean hasMentions() {
	   return !getMentions().isEmpty();
    }

    public void addMentions(Hadith newMentions) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_MENTIONS,
                                       newMentions);
    }

    public void removeMentions(Hadith oldMentions) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_MENTIONS,
                                          oldMentions);
    }


    /* ***************************************************
     * Object Property http://www.i-knex.com/ontology/hadith#refersToRootNarrator
     */
     
    public Collection<? extends WrappedIndividual> getRefersToRootNarrator() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_REFERSTOROOTNARRATOR,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasRefersToRootNarrator() {
	   return !getRefersToRootNarrator().isEmpty();
    }

    public void addRefersToRootNarrator(WrappedIndividual newRefersToRootNarrator) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_REFERSTOROOTNARRATOR,
                                       newRefersToRootNarrator);
    }

    public void removeRefersToRootNarrator(WrappedIndividual oldRefersToRootNarrator) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_REFERSTOROOTNARRATOR,
                                          oldRefersToRootNarrator);
    }


    /* ***************************************************
     * Object Property http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso
     */
     
    public Collection<? extends WrappedIndividual> getRdf_seeAlso() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_RDF_SEEALSO,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasRdf_seeAlso() {
	   return !getRdf_seeAlso().isEmpty();
    }

    public void addRdf_seeAlso(WrappedIndividual newRdf_seeAlso) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_RDF_SEEALSO,
                                       newRdf_seeAlso);
    }

    public void removeRdf_seeAlso(WrappedIndividual oldRdf_seeAlso) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_RDF_SEEALSO,
                                          oldRdf_seeAlso);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#attribute
     */
     
    public Collection<? extends Object> getAttribute() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATTRIBUTE, Object.class);
    }

    public boolean hasAttribute() {
		return !getAttribute().isEmpty();
    }

    public void addAttribute(Object newAttribute) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATTRIBUTE, newAttribute);
    }

    public void removeAttribute(Object oldAttribute) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ATTRIBUTE, oldAttribute);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#birthPlace
     */
     
    public Collection<? extends Object> getBirthPlace() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BIRTHPLACE, Object.class);
    }

    public boolean hasBirthPlace() {
		return !getBirthPlace().isEmpty();
    }

    public void addBirthPlace(Object newBirthPlace) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BIRTHPLACE, newBirthPlace);
    }

    public void removeBirthPlace(Object oldBirthPlace) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BIRTHPLACE, oldBirthPlace);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#birthYear
     */
     
    public Collection<? extends Object> getBirthYear() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BIRTHYEAR, Object.class);
    }

    public boolean hasBirthYear() {
		return !getBirthYear().isEmpty();
    }

    public void addBirthYear(Object newBirthYear) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BIRTHYEAR, newBirthYear);
    }

    public void removeBirthYear(Object oldBirthYear) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BIRTHYEAR, oldBirthYear);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#chapterNo
     */
     
    public Collection<? extends Object> getChapterNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERNO, Object.class);
    }

    public boolean hasChapterNo() {
		return !getChapterNo().isEmpty();
    }

    public void addChapterNo(Object newChapterNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERNO, newChapterNo);
    }

    public void removeChapterNo(Object oldChapterNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERNO, oldChapterNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#chapterPreface
     */
     
    public Collection<? extends Object> getChapterPreface() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERPREFACE, Object.class);
    }

    public boolean hasChapterPreface() {
		return !getChapterPreface().isEmpty();
    }

    public void addChapterPreface(Object newChapterPreface) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERPREFACE, newChapterPreface);
    }

    public void removeChapterPreface(Object oldChapterPreface) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CHAPTERPREFACE, oldChapterPreface);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#collectionName
     */
     
    public Collection<? extends Object> getCollectionName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COLLECTIONNAME, Object.class);
    }

    public boolean hasCollectionName() {
		return !getCollectionName().isEmpty();
    }

    public void addCollectionName(Object newCollectionName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COLLECTIONNAME, newCollectionName);
    }

    public void removeCollectionName(Object oldCollectionName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_COLLECTIONNAME, oldCollectionName);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#concealment
     */
     
    public Collection<? extends Object> getConcealment() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONCEALMENT, Object.class);
    }

    public boolean hasConcealment() {
		return !getConcealment().isEmpty();
    }

    public void addConcealment(Object newConcealment) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONCEALMENT, newConcealment);
    }

    public void removeConcealment(Object oldConcealment) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONCEALMENT, oldConcealment);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#deathPlace
     */
     
    public Collection<? extends Object> getDeathPlace() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEATHPLACE, Object.class);
    }

    public boolean hasDeathPlace() {
		return !getDeathPlace().isEmpty();
    }

    public void addDeathPlace(Object newDeathPlace) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEATHPLACE, newDeathPlace);
    }

    public void removeDeathPlace(Object oldDeathPlace) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEATHPLACE, oldDeathPlace);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#deathYear
     */
     
    public Collection<? extends Object> getDeathYear() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEATHYEAR, Object.class);
    }

    public boolean hasDeathYear() {
		return !getDeathYear().isEmpty();
    }

    public void addDeathYear(Object newDeathYear) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEATHYEAR, newDeathYear);
    }

    public void removeDeathYear(Object oldDeathYear) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_DEATHYEAR, oldDeathYear);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#engBookNo
     */
     
    public Collection<? extends Object> getEngBookNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGBOOKNO, Object.class);
    }

    public boolean hasEngBookNo() {
		return !getEngBookNo().isEmpty();
    }

    public void addEngBookNo(Object newEngBookNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGBOOKNO, newEngBookNo);
    }

    public void removeEngBookNo(Object oldEngBookNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGBOOKNO, oldEngBookNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#engHadithNo
     */
     
    public Collection<? extends Object> getEngHadithNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGHADITHNO, Object.class);
    }

    public boolean hasEngHadithNo() {
		return !getEngHadithNo().isEmpty();
    }

    public void addEngHadithNo(Object newEngHadithNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGHADITHNO, newEngHadithNo);
    }

    public void removeEngHadithNo(Object oldEngHadithNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGHADITHNO, oldEngHadithNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#engVolNo
     */
     
    public Collection<? extends Object> getEngVolNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGVOLNO, Object.class);
    }

    public boolean hasEngVolNo() {
		return !getEngVolNo().isEmpty();
    }

    public void addEngVolNo(Object newEngVolNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGVOLNO, newEngVolNo);
    }

    public void removeEngVolNo(Object oldEngVolNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGVOLNO, oldEngVolNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#englishReference
     */
     
    public Collection<? extends Object> getEnglishReference() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGLISHREFERENCE, Object.class);
    }

    public boolean hasEnglishReference() {
		return !getEnglishReference().isEmpty();
    }

    public void addEnglishReference(Object newEnglishReference) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGLISHREFERENCE, newEnglishReference);
    }

    public void removeEnglishReference(Object oldEnglishReference) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ENGLISHREFERENCE, oldEnglishReference);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#firstChar
     */
     
    public Collection<? extends Object> getFirstChar() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRSTCHAR, Object.class);
    }

    public boolean hasFirstChar() {
		return !getFirstChar().isEmpty();
    }

    public void addFirstChar(Object newFirstChar) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRSTCHAR, newFirstChar);
    }

    public void removeFirstChar(Object oldFirstChar) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FIRSTCHAR, oldFirstChar);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#fullHadithText
     */
     
    public Collection<? extends Object> getFullHadithText() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FULLHADITHTEXT, Object.class);
    }

    public boolean hasFullHadithText() {
		return !getFullHadithText().isEmpty();
    }

    public void addFullHadithText(Object newFullHadithText) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FULLHADITHTEXT, newFullHadithText);
    }

    public void removeFullHadithText(Object oldFullHadithText) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FULLHADITHTEXT, oldFullHadithText);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#generation
     */
     
    public Collection<? extends Object> getGeneration() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GENERATION, Object.class);
    }

    public boolean hasGeneration() {
		return !getGeneration().isEmpty();
    }

    public void addGeneration(Object newGeneration) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GENERATION, newGeneration);
    }

    public void removeGeneration(Object oldGeneration) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_GENERATION, oldGeneration);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hadithBookIntro
     */
     
    public Collection<? extends Object> getHadithBookIntro() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKINTRO, Object.class);
    }

    public boolean hasHadithBookIntro() {
		return !getHadithBookIntro().isEmpty();
    }

    public void addHadithBookIntro(Object newHadithBookIntro) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKINTRO, newHadithBookIntro);
    }

    public void removeHadithBookIntro(Object oldHadithBookIntro) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKINTRO, oldHadithBookIntro);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hadithBookNo
     */
     
    public Collection<? extends Object> getHadithBookNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKNO, Object.class);
    }

    public boolean hasHadithBookNo() {
		return !getHadithBookNo().isEmpty();
    }

    public void addHadithBookNo(Object newHadithBookNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKNO, newHadithBookNo);
    }

    public void removeHadithBookNo(Object oldHadithBookNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHBOOKNO, oldHadithBookNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hadithChapterNo
     */
     
    public Collection<? extends Object> getHadithChapterNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHCHAPTERNO, Object.class);
    }

    public boolean hasHadithChapterNo() {
		return !getHadithChapterNo().isEmpty();
    }

    public void addHadithChapterNo(Object newHadithChapterNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHCHAPTERNO, newHadithChapterNo);
    }

    public void removeHadithChapterNo(Object oldHadithChapterNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHCHAPTERNO, oldHadithChapterNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hadithGrade
     */
     
    public Collection<? extends Object> getHadithGrade() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHGRADE, Object.class);
    }

    public boolean hasHadithGrade() {
		return !getHadithGrade().isEmpty();
    }

    public void addHadithGrade(Object newHadithGrade) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHGRADE, newHadithGrade);
    }

    public void removeHadithGrade(Object oldHadithGrade) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHGRADE, oldHadithGrade);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hadithReferenceNo
     */
     
    public Collection<? extends Object> getHadithReferenceNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREFERENCENO, Object.class);
    }

    public boolean hasHadithReferenceNo() {
		return !getHadithReferenceNo().isEmpty();
    }

    public void addHadithReferenceNo(Object newHadithReferenceNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREFERENCENO, newHadithReferenceNo);
    }

    public void removeHadithReferenceNo(Object oldHadithReferenceNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHREFERENCENO, oldHadithReferenceNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hadithType
     */
     
    public Collection<? extends Object> getHadithType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTYPE, Object.class);
    }

    public boolean hasHadithType() {
		return !getHadithType().isEmpty();
    }

    public void addHadithType(Object newHadithType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTYPE, newHadithType);
    }

    public void removeHadithType(Object oldHadithType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHTYPE, oldHadithType);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hadithURL
     */
     
    public Collection<? extends Object> getHadithURL() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHURL, Object.class);
    }

    public boolean hasHadithURL() {
		return !getHadithURL().isEmpty();
    }

    public void addHadithURL(Object newHadithURL) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHURL, newHadithURL);
    }

    public void removeHadithURL(Object oldHadithURL) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HADITHURL, oldHadithURL);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#hasMaster
     */
     
    public Collection<? extends Object> getHasMaster() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMASTER, Object.class);
    }

    public boolean hasHasMaster() {
		return !getHasMaster().isEmpty();
    }

    public void addHasMaster(Object newHasMaster) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMASTER, newHasMaster);
    }

    public void removeHasMaster(Object oldHasMaster) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASMASTER, oldHasMaster);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#lineage
     */
     
    public Collection<? extends Object> getLineage() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LINEAGE, Object.class);
    }

    public boolean hasLineage() {
		return !getLineage().isEmpty();
    }

    public void addLineage(Object newLineage) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LINEAGE, newLineage);
    }

    public void removeLineage(Object oldLineage) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LINEAGE, oldLineage);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#name
     */
     
    public Collection<? extends Object> getName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NAME, Object.class);
    }

    public boolean hasName() {
		return !getName().isEmpty();
    }

    public void addName(Object newName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NAME, newName);
    }

    public void removeName(Object oldName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NAME, oldName);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#narratorChain
     */
     
    public Collection<? extends Object> getNarratorChain() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORCHAIN, Object.class);
    }

    public boolean hasNarratorChain() {
		return !getNarratorChain().isEmpty();
    }

    public void addNarratorChain(Object newNarratorChain) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORCHAIN, newNarratorChain);
    }

    public void removeNarratorChain(Object oldNarratorChain) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORCHAIN, oldNarratorChain);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#narratorID
     */
     
    public Collection<? extends Object> getNarratorID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORID, Object.class);
    }

    public boolean hasNarratorID() {
		return !getNarratorID().isEmpty();
    }

    public void addNarratorID(Object newNarratorID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORID, newNarratorID);
    }

    public void removeNarratorID(Object oldNarratorID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORID, oldNarratorID);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#narratorURL
     */
     
    public Collection<? extends Object> getNarratorURL() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORURL, Object.class);
    }

    public boolean hasNarratorURL() {
		return !getNarratorURL().isEmpty();
    }

    public void addNarratorURL(Object newNarratorURL) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORURL, newNarratorURL);
    }

    public void removeNarratorURL(Object oldNarratorURL) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_NARRATORURL, oldNarratorURL);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#office
     */
     
    public Collection<? extends Object> getOffice() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_OFFICE, Object.class);
    }

    public boolean hasOffice() {
		return !getOffice().isEmpty();
    }

    public void addOffice(Object newOffice) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_OFFICE, newOffice);
    }

    public void removeOffice(Object oldOffice) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_OFFICE, oldOffice);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#popularName
     */
     
    public Collection<? extends Object> getPopularName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POPULARNAME, Object.class);
    }

    public boolean hasPopularName() {
		return !getPopularName().isEmpty();
    }

    public void addPopularName(Object newPopularName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POPULARNAME, newPopularName);
    }

    public void removePopularName(Object oldPopularName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_POPULARNAME, oldPopularName);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#rank
     */
     
    public Collection<? extends Object> getRank() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RANK, Object.class);
    }

    public boolean hasRank() {
		return !getRank().isEmpty();
    }

    public void addRank(Object newRank) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RANK, newRank);
    }

    public void removeRank(Object oldRank) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RANK, oldRank);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#residence
     */
     
    public Collection<? extends Object> getResidence() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RESIDENCE, Object.class);
    }

    public boolean hasResidence() {
		return !getResidence().isEmpty();
    }

    public void addResidence(Object newResidence) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RESIDENCE, newResidence);
    }

    public void removeResidence(Object oldResidence) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RESIDENCE, oldResidence);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#schoolOfThought
     */
     
    public Collection<? extends Object> getSchoolOfThought() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SCHOOLOFTHOUGHT, Object.class);
    }

    public boolean hasSchoolOfThought() {
		return !getSchoolOfThought().isEmpty();
    }

    public void addSchoolOfThought(Object newSchoolOfThought) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SCHOOLOFTHOUGHT, newSchoolOfThought);
    }

    public void removeSchoolOfThought(Object oldSchoolOfThought) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SCHOOLOFTHOUGHT, oldSchoolOfThought);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#sequenceNo
     */
     
    public Collection<? extends Object> getSequenceNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEQUENCENO, Object.class);
    }

    public boolean hasSequenceNo() {
		return !getSequenceNo().isEmpty();
    }

    public void addSequenceNo(Object newSequenceNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEQUENCENO, newSequenceNo);
    }

    public void removeSequenceNo(Object oldSequenceNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SEQUENCENO, oldSequenceNo);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#teknonym
     */
     
    public Collection<? extends Object> getTeknonym() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TEKNONYM, Object.class);
    }

    public boolean hasTeknonym() {
		return !getTeknonym().isEmpty();
    }

    public void addTeknonym(Object newTeknonym) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TEKNONYM, newTeknonym);
    }

    public void removeTeknonym(Object oldTeknonym) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TEKNONYM, oldTeknonym);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#title
     */
     
    public Collection<? extends Object> getTitle() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TITLE, Object.class);
    }

    public boolean hasTitle() {
		return !getTitle().isEmpty();
    }

    public void addTitle(Object newTitle) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TITLE, newTitle);
    }

    public void removeTitle(Object oldTitle) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TITLE, oldTitle);
    }


    /* ***************************************************
     * Data Property http://www.i-knex.com/ontology/hadith#verseNo
     */
     
    public Collection<? extends Object> getVerseNo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_VERSENO, Object.class);
    }

    public boolean hasVerseNo() {
		return !getVerseNo().isEmpty();
    }

    public void addVerseNo(Object newVerseNo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_VERSENO, newVerseNo);
    }

    public void removeVerseNo(Object oldVerseNo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_VERSENO, oldVerseNo);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2000/01/rdf-schema#label
     */
     
    public Collection<? extends Object> getRdfs_label() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RDFS_LABEL, Object.class);
    }

    public boolean hasRdfs_label() {
		return !getRdfs_label().isEmpty();
    }

    public void addRdfs_label(Object newRdfs_label) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RDFS_LABEL, newRdfs_label);
    }

    public void removeRdfs_label(Object oldRdfs_label) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_RDFS_LABEL, oldRdfs_label);
    }


    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#sameAs
     */
     
    public Collection<? extends Object> getOwl_sameAs() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_OWL_SAMEAS, Object.class);
    }

    public boolean hasOwl_sameAs() {
		return !getOwl_sameAs().isEmpty();
    }

    public void addOwl_sameAs(Object newOwl_sameAs) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_OWL_SAMEAS, newOwl_sameAs);
    }

    public void removeOwl_sameAs(Object oldOwl_sameAs) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_OWL_SAMEAS, oldOwl_sameAs);
    }


}
