package HadithOntology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Jan 09 12:58:42 PKT 2022 by amna
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Believer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BELIEVER.<p>
     * 
     */
    public static final OWLClass CLASS_BELIEVER = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Believer"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Companion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPANION.<p>
     * 
     */
    public static final OWLClass CLASS_COMPANION = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Companion"));
    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/precedes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRECEDES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRECEDES = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/precedes"));

   
    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Elevated_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ELEVATED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_ELEVATED_HADITH = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Elevated_Hadith"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_HADITH = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Hadith"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/HadithBook
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHBOOK.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHBOOK = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/HadithBook"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/HadithChapter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCHAPTER.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCHAPTER = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/HadithChapter"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/HadithCollection
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCOLLECTION.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCOLLECTION = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/HadithCollection"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/HadithCollectionAuthor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCOLLECTIONAUTHOR.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCOLLECTIONAUTHOR = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/HadithCollectionAuthor"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/HadithNarrator
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHNARRATOR.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHNARRATOR = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/HadithNarrator"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/HadithText
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHTEXT = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/HadithText"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/HadithType
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHTYPE.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHTYPE = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/HadithType"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/NarratorChain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NARRATORCHAIN.<p>
     * 
     */
    public static final OWLClass CLASS_NARRATORCHAIN = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/NarratorChain"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/NarratorOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NARRATOROCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_NARRATOROCCURRENCE = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/NarratorOccurrence"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Person"));
    /* ***************************************************
     * Class http://schema.org/Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHEMA:PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_SCHEMA_PERSON = factory.getOWLClass(IRI.create("http://schema.org/Person"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/RootNarrator
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROOTNARRATOR.<p>
     * 
     */
    public static final OWLClass CLASS_ROOTNARRATOR = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/RootNarrator"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/RootNarratorOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROOTNARRATOROCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_ROOTNARRATOROCCURRENCE = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/RootNarratorOccurrence"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Sacred_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SACRED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_SACRED_HADITH = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Sacred_Hadith"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Severed_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEVERED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_SEVERED_HADITH = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Severed_Hadith"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Stopped_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STOPPED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_STOPPED_HADITH = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Stopped_Hadith"));

    /* ***************************************************
     * Class http://www.semantichadith.com/ontology/Verse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERSE.<p>
     * 
     */
    public static final OWLClass CLASS_VERSE = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/Verse"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/author
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AUTHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AUTHOR = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/author"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/containsMentionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSMENTIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSMENTIONOF = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/containsMentionOf"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasBook
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBOOK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBOOK = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasBook"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasChapter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCHAPTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCHAPTER = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasChapter"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasHadith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHADITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHADITH = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasHadith"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasHadithText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHADITHTEXT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHADITHTEXT = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasHadithText"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasHadithType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHADITHTYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHADITHTYPE = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasHadithType"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasNarrator"));

    /* ***************************************************
      * Object Property http://www.semantichadith.com/ontology/hasNarratorChain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNARRATORCHAIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNARRATORCHAIN = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasNarratorChain"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasNarratorOccurence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNARRATORSEGMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNARRATORSEGMENT = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasNarratorSegment"));


    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasRootNarratorSegment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASROOTNARRATORSEGMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASROOTNARRATORSEGMENT = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasRootNarratorSegment"));

 
   /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPART = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasPart"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/hasRootNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASROOTNARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASROOTNARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/hasRootNarrator"));


     
   /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/heardFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HEARDFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HEARDFROM = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/heardFrom"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/isPartOf"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/isPartOfBook
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFBOOK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFBOOK = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/isPartOfBook"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/isPartOfChapter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFCHAPTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFCHAPTER = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/isPartOfChapter"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/isPartOfCollection
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFCOLLECTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFCOLLECTION = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/isPartOfCollection"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/isPartOfHadith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFHADITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFHADITH = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/isPartOfHadith"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/mentionedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MENTIONEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MENTIONEDIN = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/mentionedIn"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/mentions
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MENTIONS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MENTIONS = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/mentions"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/narrated
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NARRATED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NARRATED = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/narrated"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/refersToNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERSTONARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERSTONARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/refersToNarrator"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/refersToRootNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERSTOROOTNARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERSTOROOTNARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/refersToRootNarrator"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/transferredTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TRANSFERREDTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TRANSFERREDTO = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/transferredTo"));

    /* ***************************************************
     * Object Property http://www.semantichadith.com/ontology/follows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOLLOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOLLOWS = factory.getOWLObjectProperty(IRI.create("http://www.semantichadith.com/ontology/follows"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/age
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property AGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_AGE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/age"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/attribute
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ATTRIBUTE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ATTRIBUTE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/attribute"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/birthPlace
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BIRTHPLACE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BIRTHPLACE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/birthPlace"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/birthYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BIRTHYEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BIRTHYEAR = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/birthYear"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/chapterNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERNO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/chapterNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/chapterPreface
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERPREFACE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERPREFACE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/chapterPreface"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/collectionName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COLLECTIONNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COLLECTIONNAME = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/collectionName"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/concealment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONCEALMENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CONCEALMENT = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/concealment"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/deathPlace
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEATHPLACE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEATHPLACE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/deathPlace"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/deathYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEATHYEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEATHYEAR = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/deathYear"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/engBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/engBookNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/engHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/engHadithNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/engVolNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGVOLNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGVOLNO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/engVolNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/englishReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGLISHREFERENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGLISHREFERENCE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/englishReference"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/firstChar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FIRSTCHAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FIRSTCHAR = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/firstChar"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/fullHadithText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FULLHADITHTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FULLHADITHTEXT = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/fullHadithText"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/generation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GENERATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GENERATION = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/generation"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hadithBookIntro
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKINTRO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKINTRO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithBookIntro"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hadithBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithBookNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hadithChapterNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHCHAPTERNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHCHAPTERNO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithChapterNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hadithGrade
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHGRADE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHGRADE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithGrade"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hadithReferenceNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHREFERENCENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHREFERENCENO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithReferenceNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hadithType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHTYPE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithType"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hadithURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHURL = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithURL"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/hasMaster
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMASTER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMASTER = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hasMaster"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/lineage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LINEAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LINEAGE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/lineage"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/name"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/narratorChain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORCHAIN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORCHAIN = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/narratorChain"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/narratorID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORID = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/narratorID"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/narratorURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORURL = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/narratorURL"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/office
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OFFICE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OFFICE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/office"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/popularName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POPULARNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POPULARNAME = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/popularName"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/rank
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RANK.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RANK = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/rank"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/residence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RESIDENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RESIDENCE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/residence"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/schoolOfThought
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SCHOOLOFTHOUGHT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SCHOOLOFTHOUGHT = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/schoolOfThought"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/sequenceNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SEQUENCENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SEQUENCENO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/sequenceNo"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/teknonym
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TEKNONYM.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TEKNONYM = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/teknonym"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/title
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TITLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TITLE = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/title"));

    /* ***************************************************
     * Data Property http://www.semantichadith.com/ontology/verseNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSENO = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/verseNo"));

    /* ***************************************************
     * Data Property http://www.w3.org/2000/01/rdf-schema#label
     */
        
       /**
        * A constant to give access to the Manchester OWL API representation of the data property RDFS:LABEL.<p>
        * 
        */
       public static final OWLDataProperty DATA_PROPERTY_RDFS_LABEL = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#label"));

       /* ***************************************************
        * Data Property http://www.w3.org/2002/07/owl#sameAs
        */
        
       /**
        * A constant to give access to the Manchester OWL API representation of the data property OWL:SAMEAS.<p>
        * 
        */
       public static final OWLDataProperty DATA_PROPERTY_OWL_SAMEAS = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#sameAs"));
       /* ***************************************************
        * Object Property http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso
        */
        
       /**
        * A constant to give access to the Manchester OWL API representation of the object property RDF:SEEALSO.<p>
        * 
        */
       public static final OWLObjectProperty OBJECT_PROPERTY_RDF_SEEALSO = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso"));


       /* ***************************************************
        * Class http://www.semantichadith.com/ontology/NarratorChainSegment
        */

       /**
        * A constant to give access to the Manchester OWL api representation of the class NARRATORCHAINSEGMENT.<p>
        * 
        */
       public static final OWLClass CLASS_NARRATORCHAINSEGMENT = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/NarratorChainSegment"));
       /* ***************************************************
        * Class http://www.semantichadith.com/ontology/RootNarratorChainSegment
        */

       /**
        * A constant to give access to the Manchester OWL api representation of the class ROOTNARRATORCHAINSEGMENT.<p>
        * 
        */
       public static final OWLClass CLASS_ROOTNARRATORCHAINSEGMENT = factory.getOWLClass(IRI.create("http://www.semantichadith.com/ontology/RootNarratorChainSegment"));
       /* ***************************************************
        * Data Property http://www.semantichadith.com/ontology/hadithText
        */
        
       /**
        * A constant to give access to the Manchester OWL API representation of the data property HADITHTEXT.<p>
        * 
        */
       public static final OWLDataProperty DATA_PROPERTY_HADITHTEXT = factory.getOWLDataProperty(IRI.create("http://www.semantichadith.com/ontology/hadithText"));

}
