package HadithOntology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Jan 09 12:58:42 PKT 2022 by amna
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Believer
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BELIEVER.<p>
     * 
     */
    public static final OWLClass CLASS_BELIEVER = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Believer"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Companion
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPANION.<p>
     * 
     */
    public static final OWLClass CLASS_COMPANION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Companion"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Elevated_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ELEVATED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_ELEVATED_HADITH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Elevated_Hadith"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_HADITH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Hadith"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithBook
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHBOOK.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHBOOK = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithBook"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithChapter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCHAPTER.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCHAPTER = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithChapter"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithCollection
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCOLLECTION.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCOLLECTION = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithCollection"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithCollectionAuthor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHCOLLECTIONAUTHOR.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHCOLLECTIONAUTHOR = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithCollectionAuthor"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithNarrator
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHNARRATOR.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHNARRATOR = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithNarrator"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithText
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHTEXT = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithText"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#HadithType
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HADITHTYPE.<p>
     * 
     */
    public static final OWLClass CLASS_HADITHTYPE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#HadithType"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#NarratorChain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NARRATORCHAIN.<p>
     * 
     */
    public static final OWLClass CLASS_NARRATORCHAIN = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#NarratorChain"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#NarratorOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NARRATOROCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_NARRATOROCCURRENCE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#NarratorOccurrence"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Person"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#RootNarrator
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROOTNARRATOR.<p>
     * 
     */
    public static final OWLClass CLASS_ROOTNARRATOR = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#RootNarrator"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#RootNarratorOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROOTNARRATOROCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_ROOTNARRATOROCCURRENCE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#RootNarratorOccurrence"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Sacred_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SACRED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_SACRED_HADITH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Sacred_Hadith"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Severed_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SEVERED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_SEVERED_HADITH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Severed_Hadith"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Stopped_Hadith
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STOPPED_HADITH.<p>
     * 
     */
    public static final OWLClass CLASS_STOPPED_HADITH = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Stopped_Hadith"));

    /* ***************************************************
     * Class http://www.lodislamica.me/ontology/hadithVoc#Verse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERSE.<p>
     * 
     */
    public static final OWLClass CLASS_VERSE = factory.getOWLClass(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#Verse"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#author
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AUTHOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AUTHOR = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#author"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#containsMentionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSMENTIONOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSMENTIONOF = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#containsMentionOf"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasBook
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBOOK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBOOK = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasBook"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasChapter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCHAPTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCHAPTER = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasChapter"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasHadith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHADITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHADITH = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasHadith"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasHadithText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHADITHTEXT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHADITHTEXT = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasHadithText"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasHadithType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASHADITHTYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASHADITHTYPE = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasHadithType"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasNarrator"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasNarratorChain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNARRATORCHAIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNARRATORCHAIN = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasNarratorChain"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasNarratorOccurence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASNARRATOROCCURENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASNARRATOROCCURENCE = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasNarratorOccurence"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPART = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasPart"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasRootNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASROOTNARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASROOTNARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasRootNarrator"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#hasRootNarratorOccurrence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASROOTNARRATOROCCURRENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASROOTNARRATOROCCURRENCE = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasRootNarratorOccurrence"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#heardFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HEARDFROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HEARDFROM = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#heardFrom"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#isPartOf"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#isPartOfBook
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFBOOK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFBOOK = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#isPartOfBook"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#isPartOfChapter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFCHAPTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFCHAPTER = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#isPartOfChapter"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#isPartOfCollection
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFCOLLECTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFCOLLECTION = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#isPartOfCollection"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#isPartOfHadith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFHADITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFHADITH = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#isPartOfHadith"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#mentionedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MENTIONEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MENTIONEDIN = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#mentionedIn"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#mentions
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MENTIONS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MENTIONS = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#mentions"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#narrated
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NARRATED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NARRATED = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narrated"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#refersToNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERSTONARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERSTONARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#refersToNarrator"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#refersToRootNarrator
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERSTOROOTNARRATOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERSTOROOTNARRATOR = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#refersToRootNarrator"));

    /* ***************************************************
     * Object Property http://www.lodislamica.me/ontology/hadithVoc#transferredTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TRANSFERREDTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TRANSFERREDTO = factory.getOWLObjectProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#transferredTo"));


    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#age
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property AGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_AGE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#age"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#attribute
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ATTRIBUTE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ATTRIBUTE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#attribute"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#birthPlace
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BIRTHPLACE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BIRTHPLACE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#birthPlace"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#birthYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BIRTHYEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BIRTHYEAR = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#birthYear"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#chapterNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#chapterNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#chapterPreface
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERPREFACE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERPREFACE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#chapterPreface"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#collectionName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COLLECTIONNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COLLECTIONNAME = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#collectionName"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#concealment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONCEALMENT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CONCEALMENT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#concealment"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#deathPlace
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEATHPLACE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEATHPLACE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#deathPlace"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#deathYear
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DEATHYEAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DEATHYEAR = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#deathYear"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#engBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#engBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#engHadithNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGHADITHNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGHADITHNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#engHadithNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#engVolNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGVOLNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGVOLNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#engVolNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#englishReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ENGLISHREFERENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ENGLISHREFERENCE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#englishReference"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#firstChar
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FIRSTCHAR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FIRSTCHAR = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#firstChar"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#fullHadithText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FULLHADITHTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FULLHADITHTEXT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#fullHadithText"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#generation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GENERATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GENERATION = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#generation"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookIntro
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKINTRO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKINTRO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithBookIntro"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHBOOKNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHBOOKNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithBookNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHCHAPTERNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHCHAPTERNO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithChapterNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithGrade
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHGRADE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHGRADE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithGrade"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHREFERENCENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHREFERENCENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithReferenceNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHTYPE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithType"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hadithURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HADITHURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HADITHURL = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hadithURL"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#hasMaster
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASMASTER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASMASTER = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#hasMaster"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#lineage
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LINEAGE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LINEAGE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#lineage"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#name"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#narratorChain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORCHAIN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORCHAIN = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narratorChain"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#narratorID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORID = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narratorID"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#narratorURL
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NARRATORURL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NARRATORURL = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#narratorURL"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#office
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OFFICE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OFFICE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#office"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#popularName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property POPULARNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_POPULARNAME = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#popularName"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#rank
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RANK.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RANK = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#rank"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#residence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RESIDENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RESIDENCE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#residence"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#schoolOfThought
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SCHOOLOFTHOUGHT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SCHOOLOFTHOUGHT = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#schoolOfThought"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#sequenceNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SEQUENCENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SEQUENCENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#sequenceNo"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#teknonym
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TEKNONYM.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TEKNONYM = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#teknonym"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#title
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TITLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TITLE = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#title"));

    /* ***************************************************
     * Data Property http://www.lodislamica.me/ontology/hadithVoc#verseNo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSENO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSENO = factory.getOWLDataProperty(IRI.create("http://www.lodislamica.me/ontology/hadithVoc#verseNo"));

    /* ***************************************************
     * Data Property http://www.w3.org/2000/01/rdf-schema#label
     */
        
       /**
        * A constant to give access to the Manchester OWL API representation of the data property RDFS:LABEL.<p>
        * 
        */
       public static final OWLDataProperty DATA_PROPERTY_RDFS_LABEL = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#label"));

       /* ***************************************************
        * Data Property http://www.w3.org/2002/07/owl#sameAs
        */
        
       /**
        * A constant to give access to the Manchester OWL API representation of the data property OWL:SAMEAS.<p>
        * 
        */
       public static final OWLDataProperty DATA_PROPERTY_OWL_SAMEAS = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#sameAs"));
       /* ***************************************************
        * Object Property http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso
        */
        
       /**
        * A constant to give access to the Manchester OWL API representation of the object property RDF:SEEALSO.<p>
        * 
        */
       public static final OWLObjectProperty OBJECT_PROPERTY_RDF_SEEALSO = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/1999/02/22-rdf-syntax-ns#seeAlso"));



}
